# Generated by Django 3.0.5 on 2020-07-07 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_command', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='Command',
            new_name='command',
        ),
    ]
