# Generated by Django 3.0.5 on 2020-07-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_command', '0002_auto_20200707_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='command',
            new_name='command1',
        ),
    ]
