# Generated by Django 3.0.5 on 2020-07-07 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_command', '0003_auto_20200707_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='command1',
            new_name='command',
        ),
    ]
