# Generated by Django 3.0.5 on 2020-07-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_collection', '0005_auto_20200709_1733'),
        ('manage_command', '0004_auto_20200707_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='manage_collection.Collection'),
        ),
    ]
